#!/usr/bin/env python3
"""Generate a grouped Markdown index for the repository."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "REPO_INDEX.md"

def title_for(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem.replace("-", " ").title()

def markdown_files() -> list[Path]:
    return sorted(
        path
        for path in ROOT.rglob("*.md")
        if ".git" not in path.parts
        and "__pycache__" not in path.parts
        and path.name != OUTPUT.name
    )

def sort_key(path: Path) -> tuple[int, str]:
    return (0 if path.name == "README.md" else 1, path.as_posix())

def count_files(pattern: str) -> int:
    return sum(1 for path in ROOT.rglob(pattern) if ".git" not in path.parts and "__pycache__" not in path.parts)

def mermaid_diagram_count(paths: list[Path]) -> int:
    count = 0
    for path in paths:
        count += path.read_text(encoding="utf-8").count("```mermaid")
    count += count_files("*.mmd")
    return count

def main() -> int:
    grouped: dict[str, list[Path]] = defaultdict(list)
    all_markdown = markdown_files()
    for path in all_markdown:
        rel = path.relative_to(ROOT)
        group = rel.parts[0] if len(rel.parts) > 1 else "."
        grouped[group].append(rel)

    learning_docs = [
        path
        for path in all_markdown
        if len(path.relative_to(ROOT).parts) > 1 and path.name != "README.md"
    ]
    lines = [
        "# Repository Index",
        "",
        "This file is generated by `python tools/generate_repo_index.py`.",
        "",
        "## Repository Metrics",
        "",
        "| Metric | Count |",
        "| --- | ---: |",
        f"| Markdown files indexed | {len(all_markdown)} |",
        f"| Learning Markdown files | {len(learning_docs)} |",
        f"| Major folders | {len(grouped) - (1 if '.' in grouped else 0)} |",
        f"| Mermaid diagrams and diagram sources | {mermaid_diagram_count(all_markdown)} |",
        f"| Notebooks | {count_files('*.ipynb')} |",
        f"| Python source and tools | {count_files('*.py')} |",
        "",
    ]
    ordered_groups = [group for group in ["."] if group in grouped]
    ordered_groups.extend(group for group in sorted(grouped) if group != ".")

    for group in ordered_groups:
        heading = "Root" if group == "." else f"{group}/"
        group_paths = sorted(grouped[group], key=sort_key)
        lines.extend([f"## {heading}", "", f"{len(group_paths)} files", ""])
        for rel in group_paths:
            title = title_for(ROOT / rel)
            link = rel.as_posix()
            lines.append(f"- [{title}]({link})")
        lines.append("")

    lines.extend(["## Maintenance", "", "Regenerate this file with `python tools/generate_repo_index.py`.", ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {sum(len(v) for v in grouped.values())} Markdown files.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
