#!/usr/bin/env python3
"""Generate a grouped Markdown index for the repository."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "REPO_INDEX.md"

def title_for(path: Path) -> str:
    first_line = path.read_text(encoding="utf-8").splitlines()[0]
    if first_line.startswith("# "):
        return first_line[2:].strip()
    return path.stem.replace("-", " ").title()

def markdown_files() -> list[Path]:
    return sorted(
        path
        for path in ROOT.rglob("*.md")
        if ".git" not in path.parts
        and "__pycache__" not in path.parts
        and path.name != OUTPUT.name
    )

def main() -> int:
    grouped: dict[str, list[Path]] = defaultdict(list)
    for path in markdown_files():
        rel = path.relative_to(ROOT)
        group = rel.parts[0] if len(rel.parts) > 1 else "."
        grouped[group].append(rel)

    lines = [
        "# Repository Index",
        "",
        "This file is generated by `python tools/generate_repo_index.py`.",
        "",
    ]
    for group in sorted(grouped):
        heading = "Root" if group == "." else f"{group}/"
        lines.extend([f"## {heading}", ""])
        for rel in grouped[group]:
            title = title_for(ROOT / rel)
            link = rel.as_posix()
            lines.append(f"- [{title}]({link})")
        lines.append("")

    lines.extend(["## Maintenance", "", "Regenerate this file with `python tools/generate_repo_index.py`.", ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {sum(len(v) for v in grouped.values())} Markdown files.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
